name: edgeprop
channels:
- conda-forge
- defaults

dependencies:
# Core scientific python
- numpy
- matplotlib
- python=3.7.*
- seaborn
- pip
- scikit-learn

# Jupyter Environment
- autopep8
- notebook
- ipython
- jupyter_contrib_nbextensions
- jupyter
- nb_conda

# Web app / visualization
- bokeh
- holoviews

- pip:
    - networkx==2.4.*
    - panel
    - argparse
    - nbclean
    - tqdm
    - pathos  # for parmap
